### ISSUE TITLE
node_modules怎么解压

### ISSUE THREAD

**Issue by jacksuc** [Cherrison/CrackMinApp#10]
是直接解压到当前文件夹下（提示npm有冲突），还是解压到node_modules文件夹下？谢谢。
解压到node_modules文件夹下后测试你带的测试包未能正确完成。Unpack file D:\Program... 后面就没有了。是不是与我本机已经安装了node和npm有关。

![2019-05-19_023907](https://user-images.githubusercontent.com/82919/57973684-6f17a800-79df-11e9-8d2a-f59ad5ef3a05.png)

**Comment by Cherrison** [comment]
就直接在我放压缩包那里点一下压缩文件就行

**Comment by jacksuc** [comment]
> 就直接在我放压缩包那里点一下压缩文件就行

你看我上面的截图。编译不了。显示执行完成，但却没有文件生成。

**Comment by jacksuc** [comment]
> 就直接在我放压缩包那里点一下压缩文件就行

Unpack file D:\Progam...  后面就没有了。
