### ISSUE TITLE
编译不出来

### ISSUE THREAD

**Issue by kangaroo711** [Cherrison/CrackMinApp#14]
![image](https://user-images.githubusercontent.com/39984782/59321893-798b4000-8d06-11e9-8d4f-0bd429483750.png)

**Comment by kangaroo711** [comment]
解决了,解决办法是一定要把文件夹放在D盘

**Comment by pangchengyong** [comment]
![image](https://user-images.githubusercontent.com/15402318/61607692-834b8000-ac82-11e9-968a-bf7b99cfc054.png)
 您好 这个怎么解决呀。无法编译
