### ISSUE TITLE
为什么不能用呀

### ISSUE THREAD

**Issue by xiaomao996688** [Cherrison/CrackMinApp#19]
![image](https://user-images.githubusercontent.com/34624856/67563581-94110380-f753-11e9-86b5-5ce308f275bb.png)

**Comment by xiaomao996688** [comment]
Unpack file E:/unpakage/wxappUnpacker-master/APP.wxapkg...





  dataLength:  1437958353
  lastMark: 0x16
E:\unpakage\CrackMinApp-master\nodejs\nodejs\wuWxapkg.js:20
        if(firstMark!=0xbe||lastMark!=0xed)throw Error("Magic number is not corr
ect!");
                                           ^

Error: Magic number is not correct!
    at header (E:\unpakage\CrackMinApp-master\nodejs\nodejs\wuWxapkg.js:20:43)
    at wu.get.buf (E:\unpakage\CrackMinApp-master\nodejs\nodejs\wuWxapkg.js:111:
35)
    at ioLimit.runWithCb (E:\unpakage\CrackMinApp-master\nodejs\nodejs\wuLib.js:
80:8)
    at agent (E:\unpakage\CrackMinApp-master\nodejs\nodejs\wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_conte
xt.js:53:3)

**Comment by xiaomao996688** [comment]
这是什么问题呀

**Comment by Cherrison** [comment]
试一下  develop分支下的那个版本

**Comment by xiaomao996688** [comment]
好滴

**Comment by xiaomao996688** [comment]
![image](https://user-images.githubusercontent.com/34624856/67620992-f85cc180-f83e-11e9-95a9-d48196727ef4.png)
还是这样不行啊。

**Comment by Cherrison** [comment]
emm 我这个好像只能在d盘运行。。。

**Comment by xiaomao996688** [comment]
还是不行，我加你一个好友把我的qq97045924

**Comment by Cherrison** [comment]
我就这样设计的 我很讨厌东西装c盘 影响系统速度   c盘应该只有系统文件:smile:

**Comment by Cherrison** [comment]
你加我吧 1197750415

**Comment by galikeoy** [comment]
> emm 我这个好像只能在d盘运行。。。

还真的是，只能放在D:/CrackMinApp
![image.png](https://ws1.sinaimg.cn/large/006qqcX8gy1g8dtfcxaoqj31bw0mnq8x.jpg)

**Comment by yuwenrong520** [comment]
付费解决反编译过程中的任何问题，QQ1553105644

**Comment by kolf** [comment]
> 还是不行，我加你一个好友把我的qq97045924

解决了吗？
