### ISSUE TITLE
执行成功没反应

### ISSUE THREAD

**Issue by iqiqiya** [Cherrison/CrackMinApp#25]
如题，执行倒是成功了，就是没效果
![image](https://user-images.githubusercontent.com/43666095/69403405-7aa0ae80-0d35-11ea-91f6-53b51674466a.png)
按照其他issues的方案说只能放D盘用，但是经过实测，不成功

**Comment by Cherrison** [comment]
请仔细看看我的说明。。。 而且issue里 有人跟你一样的问题

**Comment by Uukins** [comment]
> 请仔细看看我的说明。。。而且问题里有人有人跟你一样的问题

老哥,解出来没有app.js咋办

**Comment by iqiqiya** [comment]
成功了 谢谢 原来必须要使用develop分支， 感觉最好在README.md加上说明趴
