### ISSUE TITLE
没有反应

### ISSUE THREAD

**Issue by easy868** [Cherrison/CrackMinApp#28]
Microsoft Windows [版本 10.0.18362.535]
(c) 2019 Microsoft Corporation。保留所有权利。

D:\CrackMinApp-master>D:

D:\CrackMinApp-master>cd D:\CrackMinApp-master\nodejs\nodejs

D:\CrackMinApp-master\nodejs\nodejs>node .\wuWxapkg.js D:\CrackMinApp-master\wxapkg\_48489573_120.wxapkg&exit

**Comment by easy868** [comment]
大佬这怎么解决？

**Comment by Gumpsj** [comment]
被强了下不下来，，，

**Comment by Cherrison** [comment]
exit
