### ISSUE TITLE
解压出现错误

### ISSUE THREAD

**Issue by yudiya** [Cherrison/CrackMinApp#3]
![QQ图片20190324142902](https://user-images.githubusercontent.com/24709058/54875858-3aed9400-4e41-11e9-99f4-f3e139fc0bd4.png)

**Comment by Cherrison** [comment]
WinRAR

**Comment by Cherrison** [comment]
我自己用一点问题都没有。。。
一发这上面就出问题(O_O)？

**Comment by yudiya** [comment]
> 我自己用一点问题都没有。。。
> 一发这上面就出问题(O_O)？

后来解压好了

**Comment by Cherrison** [comment]
。。。。

**Comment by donydex** [comment]
> > 我自己用一点问题都没有。。。
> > 一发这上面就出问题(O_O)？
> 
> 后来解压好了

我也碰到一样的问题，求问如何解决呀
