### ISSUE TITLE
试了几个小程序全是编译不出wxss文件

### ISSUE THREAD

**Issue by shopdown** [Cherrison/CrackMinApp#9]
试了几个小程序全是编译不出wxss文件  希望能修复一下

**Comment by Cherrison** [comment]
可能是新版的小程序吧 太新的有的确实弄不了 因为有的不是原始开发的 原生开发的才支持比较好

**Comment by qq239574** [comment]
确实解压不出来wxss

**Comment by shopdown** [comment]
还是那个node文件有问题，另一个人的文件就可以直接还原出wxss文件 ，不过他只给我演示了，没有给我文件 ，楼主有时间可以研究一下

**Comment by Cherrison** [comment]
### 另一个人？ 谁啊
